/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StateArraysRouteImport } from './routes/state-arrays'
import { Route as StateRouteImport } from './routes/state'
import { Route as RenderingListsRouteImport } from './routes/rendering-lists'
import { Route as PropsRouteImport } from './routes/props'
import { Route as HowToInitializeAReactProjectRouteImport } from './routes/how-to-initialize-a-react-project'
import { Route as HowToAddRoutingRouteImport } from './routes/how-to-add-routing'
import { Route as ExampleSectionsRouteImport } from './routes/example-sections'
import { Route as IndexRouteImport } from './routes/index'

const StateArraysRoute = StateArraysRouteImport.update({
  id: '/state-arrays',
  path: '/state-arrays',
  getParentRoute: () => rootRouteImport,
} as any)
const StateRoute = StateRouteImport.update({
  id: '/state',
  path: '/state',
  getParentRoute: () => rootRouteImport,
} as any)
const RenderingListsRoute = RenderingListsRouteImport.update({
  id: '/rendering-lists',
  path: '/rendering-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const PropsRoute = PropsRouteImport.update({
  id: '/props',
  path: '/props',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToInitializeAReactProjectRoute =
  HowToInitializeAReactProjectRouteImport.update({
    id: '/how-to-initialize-a-react-project',
    path: '/how-to-initialize-a-react-project',
    getParentRoute: () => rootRouteImport,
  } as any)
const HowToAddRoutingRoute = HowToAddRoutingRouteImport.update({
  id: '/how-to-add-routing',
  path: '/how-to-add-routing',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleSectionsRoute = ExampleSectionsRouteImport.update({
  id: '/example-sections',
  path: '/example-sections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/example-sections': typeof ExampleSectionsRoute
  '/how-to-add-routing': typeof HowToAddRoutingRoute
  '/how-to-initialize-a-react-project': typeof HowToInitializeAReactProjectRoute
  '/props': typeof PropsRoute
  '/rendering-lists': typeof RenderingListsRoute
  '/state': typeof StateRoute
  '/state-arrays': typeof StateArraysRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/example-sections': typeof ExampleSectionsRoute
  '/how-to-add-routing': typeof HowToAddRoutingRoute
  '/how-to-initialize-a-react-project': typeof HowToInitializeAReactProjectRoute
  '/props': typeof PropsRoute
  '/rendering-lists': typeof RenderingListsRoute
  '/state': typeof StateRoute
  '/state-arrays': typeof StateArraysRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/example-sections': typeof ExampleSectionsRoute
  '/how-to-add-routing': typeof HowToAddRoutingRoute
  '/how-to-initialize-a-react-project': typeof HowToInitializeAReactProjectRoute
  '/props': typeof PropsRoute
  '/rendering-lists': typeof RenderingListsRoute
  '/state': typeof StateRoute
  '/state-arrays': typeof StateArraysRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/example-sections'
    | '/how-to-add-routing'
    | '/how-to-initialize-a-react-project'
    | '/props'
    | '/rendering-lists'
    | '/state'
    | '/state-arrays'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/example-sections'
    | '/how-to-add-routing'
    | '/how-to-initialize-a-react-project'
    | '/props'
    | '/rendering-lists'
    | '/state'
    | '/state-arrays'
  id:
    | '__root__'
    | '/'
    | '/example-sections'
    | '/how-to-add-routing'
    | '/how-to-initialize-a-react-project'
    | '/props'
    | '/rendering-lists'
    | '/state'
    | '/state-arrays'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExampleSectionsRoute: typeof ExampleSectionsRoute
  HowToAddRoutingRoute: typeof HowToAddRoutingRoute
  HowToInitializeAReactProjectRoute: typeof HowToInitializeAReactProjectRoute
  PropsRoute: typeof PropsRoute
  RenderingListsRoute: typeof RenderingListsRoute
  StateRoute: typeof StateRoute
  StateArraysRoute: typeof StateArraysRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/state-arrays': {
      id: '/state-arrays'
      path: '/state-arrays'
      fullPath: '/state-arrays'
      preLoaderRoute: typeof StateArraysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/state': {
      id: '/state'
      path: '/state'
      fullPath: '/state'
      preLoaderRoute: typeof StateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rendering-lists': {
      id: '/rendering-lists'
      path: '/rendering-lists'
      fullPath: '/rendering-lists'
      preLoaderRoute: typeof RenderingListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/props': {
      id: '/props'
      path: '/props'
      fullPath: '/props'
      preLoaderRoute: typeof PropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-initialize-a-react-project': {
      id: '/how-to-initialize-a-react-project'
      path: '/how-to-initialize-a-react-project'
      fullPath: '/how-to-initialize-a-react-project'
      preLoaderRoute: typeof HowToInitializeAReactProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-add-routing': {
      id: '/how-to-add-routing'
      path: '/how-to-add-routing'
      fullPath: '/how-to-add-routing'
      preLoaderRoute: typeof HowToAddRoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example-sections': {
      id: '/example-sections'
      path: '/example-sections'
      fullPath: '/example-sections'
      preLoaderRoute: typeof ExampleSectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExampleSectionsRoute: ExampleSectionsRoute,
  HowToAddRoutingRoute: HowToAddRoutingRoute,
  HowToInitializeAReactProjectRoute: HowToInitializeAReactProjectRoute,
  PropsRoute: PropsRoute,
  RenderingListsRoute: RenderingListsRoute,
  StateRoute: StateRoute,
  StateArraysRoute: StateArraysRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
